= Список ссылок на карточки версионного файла

Идентификатор: `065E13F8-4E13-4E47-9E2A-A5F86E6439AA`

Псевдоним: `CardFileList`

== Секции карточки

=== Ссылки на файлы

* Идентификатор: `21122F33-1727-446A-8348-D5BD0CA9FEFD`

* Псевдоним: `Files`

* Тип секции: `coll`

* Название: _Ссылки на файлы_

.Поля секции Ссылки на файлы
|===
|Псевдоним|Название|Тип поля|Размер|Дополнительная информация 

a|`File`
a|`Файл`
a|`refcardid`
a|`Идентификатор типа: 6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3

Идентификатор секции: 2FDE03C2-FF87-4E42-A8C2-7CED181977FB

Поля ссылки: 
FileName`

a|`HardFile`
a|`Сильная ссылка на файл`
a|`refcardid`
a|`Идентификатор типа: 6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3

Идентификатор секции: 2FDE03C2-FF87-4E42-A8C2-7CED181977FB

Поля ссылки: 
HardFileName`

a|`AuthorID`
a|`Автор`
a|`refid`
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`



a|`CreationDate`
a|`Дата создания`
a|`datetime`

a|`Comment`
a|`Комментарий`
a|`unitext`

a|`LoopNum`
a|`Номер цикла`
a|`int`

a|`Stage`
a|`Этап`
a|`refcardid`
a|`Идентификатор типа: 35E7139A-82B8-425D-AB14-ADC2DB757D7A

Идентификатор секции: 381CB937-019E-4413-A2BD-646BE7F7250E

`

a|`VersionToShow`
a|`Версия для отображения`
a|`refid`
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`



a|`Type`
a|`Тип файла`
a|`int`

a|`DocVerFileId`
a|`Идентификатор карточки версий в документе`
a|`refcardid`
a|`Идентификатор типа: 6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3

Идентификатор секции: 2FDE03C2-FF87-4E42-A8C2-7CED181977FB

`

|===
