= Справочник типов папок

Идентификатор: `C89F55B5-C400-4658-8F6A-D3848294F386`

Псевдоним: `FolderTypesCard`

Название: _Справочник типов папок_

== Секции карточки

=== Типы папок

Идентификатор: `44AA9D10-07BA-4207-A925-F5F366659E9D`
Псевдоним: `FolderTypes`
Тип секции: `tree`
Название: _Типы папок_

.Поля секции Типы папок
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|256
a|

a|`DisableSubfolders`
a|_Не допускается создавать подчиненные папки_
a|`bool`
a|
a|

a|`DisableCards`
a|_Не допускается создавать карточки_
a|`bool`
a|
a|

a|`PropCardID`
a|_Карточка папки_
a|`refcardid`
a|
a|

a|`DefaultViewID`
a|_Представление по умолчанию_
a|`refid`
a|
a|* Идентификатор типа: `17F8F0B3-7E93-45E9-B250-EED4E93F3FA3`
* Идентификатор секции: `A6B842C8-4876-4B5A-BFD7-7A9BB2CEA657`


a|`DefaultTemplateID`
a|_Шаблон по умолчанию_
a|`refid`
a|
a|* Идентификатор типа: `A7F9784B-96A4-4B3E-B820-2E714A2A1463`
* Идентификатор секции: `E46D10A3-4DDC-40A8-B32F-9C3216B69708`


a|`URL`
a|_URL_
a|`unistring`
a|512
a|

a|`DefaultStyle`
a|_Вид отображения_
a|`enum`
a|
a|.Значения
* Отображается представление = 1
* Отображается карточка = 2
* Отображается HTML страница = 4
* Отображается представление дайджест = 8


a|`Icon`
a|_Значок папки_
a|`image`
a|
a|

a|`EnableDigest`
a|_Разрешить использование дайджеста_
a|`bool`
a|
a|

a|`EnableAutorefresh`
a|_Разрешить автоматическое обновление_
a|`bool`
a|
a|

a|`AutorefreshTimeout`
a|_Интервал автоматического обновления_
a|`int`
a|
a|

a|`ViewCycleCount`
a|_Ограничение на количество выводимых записей_
a|`int`
a|
a|

a|`HighlightUnread`
a|_Подсвечивать непрочитанные карточки_
a|`bool`
a|
a|

a|`DisablePropEdit`
a|_Запретить изменение свойств папки пользователю_
a|`bool`
a|
a|

a|`RestrictViews`
a|_Ограничивать представления_
a|`bool`
a|
a|

a|`RestrictTemplates`
a|_Ограничивать шаблоны_
a|`bool`
a|
a|

a|`RestrictCardTypes`
a|_Ограничивать виды карточек_
a|`bool`
a|
a|

a|`RestrictFolderTypes`
a|_Ограничивать виды папок_
a|`bool`
a|
a|

a|`CreateFolderCard`
a|_Создавать новую карточку папки_
a|`bool`
a|
a|

a|`FolderCardLocation`
a|_Размещение карточек папок_
a|`refid`
a|
a|* Идентификатор типа: `DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2`
* Идентификатор секции: `FE27631D-EEEA-4E2E-A04C-D4351282FB55`


a|`EnableRegularCreation`
a|_Позволять создание подпапок без типа_
a|`bool`
a|
a|

a|`NoClientSortOnFirstOpen`
a|_Не использовать клиентскую сортировку при первом показе представления_
a|`bool`
a|
a|

|===

=== Разрешенные виды карточек

Идентификатор: `B4DB4C03-D225-4EFD-AB57-375275798404`
Псевдоним: `AllowedCardTypes`
Тип секции: `coll`
Название: _Разрешенные виды карточек_

.Поля секции Разрешенные виды карточек
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`TypeID`
a|_Идентификатор типа карточки_
a|`uniqueid`
a|
a|

a|`AccessID`
a|_Описатель прав доступа к типу_
a|`sdid`
a|
a|

|===

=== Представления папки

Идентификатор: `46BF1886-CE77-471C-95DC-560F5D952B82`
Псевдоним: `AllowedViews`
Тип секции: `coll`
Название: _Представления папки_

.Поля секции Представления папки
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ViewID`
a|_Идентификатор представления_
a|`uniqueid`
a|
a|

a|`AccessID`
a|_Описатель прав доступа к представлению_
a|`sdid`
a|
a|

|===

=== Шаблоны папки

Идентификатор: `DB0D4513-9B62-47D5-9E1B-B242F0BA83D6`
Псевдоним: `AllowedTemplates`
Тип секции: `coll`
Название: _Шаблоны папки_

.Поля секции Шаблоны папки
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`TemplateID`
a|_Поле_
a|`refid`
a|
a|* Идентификатор типа: `A7F9784B-96A4-4B3E-B820-2E714A2A1463`
* Идентификатор секции: `E46D10A3-4DDC-40A8-B32F-9C3216B69708`


|===

=== Разрешенные виды папок

Идентификатор: `7B94A4FD-45C6-417A-AF75-57587BE22064`
Псевдоним: `AllowedFolderTypes`
Тип секции: `coll`
Название: _Разрешенные виды папок_

.Поля секции Разрешенные виды папок
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`FolderTypeID`
a|_Вид папки_
a|`refid`
a|
a|* Идентификатор типа: `C89F55B5-C400-4658-8F6A-D3848294F386`
* Идентификатор секции: `44AA9D10-07BA-4207-A925-F5F366659E9D`


a|`AccessID`
a|_Описатель прав доступа к типу_
a|`sdid`
a|
a|

|===

