= Карточка сохраненных поисковых запросов

Идентификатор: `05E4BE46-6304-42A7-A780-FD07F7541AF0`

Псевдоним: `SavedSearchCard`

Название: _Карточка сохраненных поисковых запросов_

== Секции карточки

=== Группы запросов

Идентификатор: `C17B7783-42C4-45CB-A66B-05CC634C7EB0`
Псевдоним: `Groups`
Тип секции: `tree`
Название: _Группы запросов_

.Поля секции Группы запросов
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Имя_
a|`unistring`
a|256
a|

|===

=== Сохраненные поисковые запросы

Идентификатор: `FB2AC41F-1911-4F7C-B631-18CFAEB311BD`
Псевдоним: `Queries`
Тип секции: `coll`
Название: _Сохраненные поисковые запросы_

.Поля секции Сохраненные поисковые запросы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|256
a|

a|`Text`
a|_Текст запроса_
a|`unitext`
a|
a|

a|`Hidden`
a|_Видимость_
a|`bool`
a|
a|

a|`Modified`
a|_Modified_
a|`bool`
a|
a|

a|`QueryFileID`
a|_Идентификатор файла текста запроса_
a|`fileid`
a|
a|

a|`DisabledAutogenerate`
a|_Отключено автоматическое пересоздание хранимых процедур_
a|`bool`
a|
a|

a|`DisabledSecurity`
a|_Выключена проверка безопасности_
a|`bool`
a|
a|

|===

=== Сохраненные разметки поисковых запросов

Идентификатор: `DC8A71DC-D2BB-4875-8B9F-0BBFF04383F7`
Псевдоним: `Layouts`
Тип секции: `coll`
Название: _Сохраненные разметки поисковых запросов_

.Поля секции Сохраненные разметки поисковых запросов
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|256
a|

a|`Text`
a|_Текст разметки_
a|`unitext`
a|
a|

a|`LayoutFileID`
a|_Идентификатор файла текста разметки запроса_
a|`fileid`
a|
a|

|===

=== Локализация

Идентификатор: `366234F5-1EA5-47CC-9506-B7BCEB08B061`
Псевдоним: `LocalizationsQueries`
Тип секции: `coll`
Название: _Локализация_

.Поля секции Локализация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`LocaleID`
a|_Идентификатор локали_
a|`int`
a|
a|

a|`Name`
a|_Локализованное имя_
a|`unistring`
a|256
a|

|===

=== Локализация

Идентификатор: `F7CDD0E8-1CD9-4E76-A1B3-4E0432C71E6B`
Псевдоним: `Localizations`
Тип секции: `coll`
Название: _Локализация_

.Поля секции Локализация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`LocaleID`
a|_Идентификатор локали_
a|`int`
a|
a|

a|`Name`
a|_Локализованное имя_
a|`unistring`
a|256
a|

|===

