= Группа заданий

Идентификатор: `2182E2A5-22A9-471F-9D65-E45DEEAE1C73`

Псевдоним: `CardTaskGroup`

Название: _Группа заданий_

== Секции карточки

=== Системные свойства

Идентификатор: `6A5AC0EA-077D-4C0A-A44A-A68C7C4AF490`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Бизнес-процессы

Идентификатор: `E5B0BB1A-4862-4C18-A558-0B92BE789696`
Псевдоним: `Processes`
Тип секции: `coll`
Название: _Бизнес-процессы_

.Поля секции Бизнес-процессы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ProcessId`
a|_Ссылка на процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`


a|`ProcessKind`
a|_Вид процесса_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `FF977158-5035-4494-AAD2-9FD0C708A7EC`


|===

=== Основная информация

Идентификатор: `7A6593BB-0BDB-4082-B43B-8F26594EFF91`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Основная информация_

.Поля секции Основная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|480
a|

a|`Author`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Content`
a|_Содержание_
a|`unitext`
a|
a|

a|`ExecutionType`
a|_Тип выполнения этапа_
a|`enum`
a|
a|.Значения
* Последовательный = 0
* Параллельный = 1


a|`StartDate`
a|_Дата начала плановая_
a|`datetime`
a|
a|

a|`EndDate`
a|_Дата завершения плановая_
a|`datetime`
a|
a|

a|`Duration`
a|_Длительность (ч)_
a|`float`
a|
a|

a|`Laboriousness`
a|_Трудоемкость(ч)_
a|`float`
a|
a|

a|`Urgency`
a|_Срочность_
a|`enum`
a|
a|.Значения
* Низкая = 1
* Нормальная = 2
* Высокая = 3


a|`OnControl`
a|_На контроле_
a|`bool`
a|
a|

a|`Controller`
a|_Контролер_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ControlDate`
a|_Дата контроля_
a|`datetime`
a|
a|

a|`RequiresAcceptance`
a|_Требуется приёмка_
a|`bool`
a|
a|

a|`ResponsiblePerformer`
a|_Ответственный исполнитель_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ReferenceList`
a|_ReferenceList_
a|`refcardid`
a|
a|* Идентификатор типа: `C9B39BEF-1047-407B-9324-8EC00D64FBEE`


a|`TaskList`
a|_Задания_
a|`refcardid`
a|
a|* Идентификатор типа: `4F34CC37-85AC-4D15-B694-2950E7F61055`


a|`PerformanceProcess`
a|_Процесс обработки_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`


a|`ControlHour`
a|_Проконтролировать за N часов до завершения задания_
a|`float`
a|
a|

a|`KindControl`
a|_Вид контроля_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`WorkGroup`
a|_Рабочая группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`MessagesId`
a|_Карточка сообщений_
a|`refcardid`
a|
a|* Идентификатор типа: `23A98E72-8C75-4B99-A3E6-3DA5853B3CA9`


a|`ResponsibleTaskId`
a|_Идентификатор задания ответственного исполнителя_
a|`refcardid`
a|
a|

a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`ParentDocument`
a|_Родительский документ_
a|`refcardid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `30EB9B87-822B-4753-9A50-A1825DCA1B74`


|===

=== Выбранные исполнители

Идентификатор: `FD25E1C4-40C9-4A32-952E-7CE66A48958C`
Псевдоним: `SelectedPerformers`
Тип секции: `coll`
Название: _Выбранные исполнители_

.Поля секции Выбранные исполнители
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Unit`
a|_Подразделение_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


a|`Group`
a|_Группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`Role`
a|_Роль_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `F6927A03-5BCE-4C7E-9C8F-E61C6D9F256E`


a|`SearchWord`
a|_Поисковое слово_
a|`uniqueid`
a|
a|

a|`Order`
a|_Номер_
a|`int`
a|
a|

|===

=== Настройки

Идентификатор: `FA6DEEFD-1546-4941-B5E5-63C24197C3DE`
Псевдоним: `Presets`
Тип секции: `struct`
Название: _Настройки_

.Поля секции Настройки
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`StartDate`
a|_Дата начала плановая_
a|`datetime`
a|
a|

a|`EndDate`
a|_Дата завершения плановая_
a|`datetime`
a|
a|

a|`Duration`
a|_Длительность (ч)_
a|`float`
a|
a|

a|`Laboriousness`
a|_Трудоемкость(ч)_
a|`float`
a|
a|

a|`Reminder`
a|_Напомнить за N часов до срока завершения задания._
a|`float`
a|
a|

a|`ReminderDate`
a|_Дата напоминания_
a|`datetime`
a|
a|

a|`Comments`
a|_Комментарии_
a|`unistring`
a|2048
a|

a|`UseOwnSettings`
a|_Использовать индивидуальные настройки_
a|`bool`
a|
a|

a|`AllowDelegateToAnyEmployee`
a|_Разрешено делегирование вручную любому сотруднику_
a|`bool`
a|
a|

a|`AllowDelegateToEmployeeFromList`
a|_Разрешено делегирование вручную сотруднику из списка_
a|`bool`
a|
a|

a|`RequestCommentAtTaskRejection`
a|_Запрашивать комментарий при отклонении задания_
a|`bool`
a|
a|

a|`UseBusinessCalendar`
a|_Использовать бизнес-календарь_
a|`bool`
a|
a|

a|`AllowDelegateManual`
a|_Разрешено делегировать вручную_
a|`bool`
a|
a|

a|`DelegateToDeputy`
a|_Разрешить делегирование заместителю при неактивности исполнителя_
a|`bool`
a|
a|

a|`SeparateTasks`
a|_Создавать отдельное задание для каждого сотрудника_
a|`bool`
a|
a|

a|`ReportFileRequired`
a|_Запрашивать файл отчёта_
a|`bool`
a|
a|

a|`ReportRequired`
a|_Ввести отчет_
a|`bool`
a|
a|

a|`RoutingType`
a|_Маршрутизация_
a|`enum`
a|
a|.Значения
* По умолчанию = 0
* Онлайн задание = 1
* Задача Почтового клиента = 2
* Ссылка на задание = 3
* Письмо с описанием = 4


|===

=== Настройка исполнителей

Идентификатор: `65EEB770-E81B-4E59-8BF9-71DB3451A949`
Псевдоним: `DelegationPresets`
Тип секции: `coll`
Название: _Настройка исполнителей_

.Поля секции Настройка исполнителей
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Unit`
a|_Подразделение_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


a|`Group`
a|_Группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`Role`
a|_Роль_
a|`refid`
a|
a|* Идентификатор типа: `7984F2CE-9345-4C59-B66B-7125DD9195A1`
* Идентификатор секции: `1C088782-C467-4FB0-B988-D5C5235500A1`


a|`SearchWord`
a|_Поисковое слово_
a|`uniqueid`
a|
a|

|===

