= Согласование

Идентификатор: `04280BC4-A660-4AEB-866F-F3ECE579D945`

Псевдоним: `CardReconcile`

Название: _Согласование_

== Секции карточки

=== Системные свойства

Идентификатор: `1375AE26-898A-49E9-87BE-A4F6AAB64BA8`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`
Поля ссылки: 
Kind_Name

|===

=== Номера

Идентификатор: `EC030CBB-7150-4C1C-A935-509BD0085481`
Псевдоним: `Numbers`
Тип секции: `coll`
Название: _Номера_

.Поля секции Номера
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`NumericPart`
a|_Числовая часть_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `D47F2C38-6553-4864-BAFF-0BC4D3A85290`


a|`Number`
a|_Номер_
a|`string`
a|
a|

|===

=== Бизнес-процессы

Идентификатор: `DB01C4C2-7096-44E5-961D-3DA521C4FEBC`
Псевдоним: `Processes`
Тип секции: `coll`
Название: _Бизнес-процессы_

.Поля секции Бизнес-процессы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ProcessId`
a|_Ссылка на процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`


a|`ProcessKind`
a|_Вид процесса_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `FF977158-5035-4494-AAD2-9FD0C708A7EC`


|===

=== Информация о согласовании

Идентификатор: `35473281-BCEB-415A-8603-74549421037E`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Информация о согласовании_

.Поля секции Информация о согласовании
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Number`
a|_Номер_
a|`refid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`
* Идентификатор секции: `EC030CBB-7150-4C1C-A935-509BD0085481`


a|`Document`
a|_Документ_
a|`refcardid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `E3E14386-27A4-4D24-96CE-9907CDCC438B`


a|`Author`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Initiator`
a|_Инициатор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Consolidator`
a|_Консолидатор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Remark`
a|_Пояснение_
a|`unitext`
a|
a|

a|`Stage`
a|_Этап_
a|`int`
a|
a|

a|`ControlDate`
a|_Контрольный срок_
a|`datetime`
a|
a|

a|`TaskList`
a|_Список заданий_
a|`refcardid`
a|
a|* Идентификатор типа: `4F34CC37-85AC-4D15-B694-2950E7F61055`
* Идентификатор секции: `9BC6B0E9-A809-43F1-A27F-323A28D1B010`


a|`ReconcileFileList`
a|_Список файлов на согласование_
a|`refcardid`
a|
a|* Идентификатор типа: `065E13F8-4E13-4E47-9E2A-A5F86E6439AA`


a|`Disagreements`
a|_Протокол разногласий_
a|`refcardid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `30EB9B87-822B-4753-9A50-A1825DCA1B74`


a|`Protocol`
a|_Протокол согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `30EB9B87-822B-4753-9A50-A1825DCA1B74`


a|`Title`
a|_Название_
a|`unistring`
a|
a|

a|`Result`
a|_Результат_
a|`int`
a|
a|

a|`Path`
a|_Маршрут_
a|`refcardid`
a|
a|* Идентификатор типа: `6CA327B1-C44F-4751-82C0-17FB33747E46`


a|`FileList`
a|_Список файлов_
a|`refcardid`
a|
a|* Идентификатор типа: `065E13F8-4E13-4E47-9E2A-A5F86E6439AA`


a|`MessagesId`
a|_Карточка сообщений_
a|`refcardid`
a|
a|

a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`CurrentProcess`
a|_Текущий основной процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`


a|`CreatedPath`
a|_Созданный маршрут_
a|`refcardid`
a|
a|

|===

=== Системная секция

Идентификатор: `CBD7D0BA-90F4-4326-B600-A871FD2682CB`
Псевдоним: `Service`
Тип секции: `struct`
Название: _Системная секция_

.Поля секции Системная секция
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Hint`
a|_Подсказка_
a|`unistring`
a|
a|

a|`Files`
a|_Файлы_
a|`refcardid`
a|
a|* Идентификатор типа: `C9B39BEF-1047-407B-9324-8EC00D64FBEE`
* Идентификатор секции: `568CE0A6-7096-43CC-9800-E0B268B14CC4`


a|`CurrentStep`
a|_Текущий шаг_
a|`int`
a|
a|

a|`StageStartTime`
a|_Время запуска текущего этапа согласования_
a|`datetime`
a|
a|

a|`ConsolidatedVerID`
a|_Идентификатор консолидируемой версии_
a|`refid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`


a|`SignatureList`
a|_Список подписей_
a|`refcardid`
a|
a|* Идентификатор типа: `CA25A38B-C65E-4A97-94EE-8E5067A6BECA`
* Идентификатор секции: `4A1AC881-DCBD-42C2-9C7A-E1DE7723400A`


a|`CardFound`
a|_Карточка найдена мониторингом_
a|`bool`
a|
a|

a|`TasksSent`
a|_Количество разосланных заданий_
a|`int`
a|
a|

a|`TotalTurns`
a|_Общее количество шагов_
a|`int`
a|
a|

a|`WasARejection`
a|_Был отказ на этапе_
a|`bool`
a|
a|

|===

=== Список участников согласования

Идентификатор: `0E3B35F2-7FC4-4968-BF5B-97803BFAE34E`
Псевдоним: `MatchingList`
Тип секции: `coll`
Название: _Список участников согласования_

.Поля секции Список участников согласования
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Turn`
a|_Очередь_
a|`int`
a|
a|

a|`Excluded`
a|_Временно исключен_
a|`bool`
a|
a|

a|`FileRights`
a|_Права на файлы_
a|`unistring`
a|
a|

a|`Deadline`
a|_Срок согласования_
a|`datetime`
a|
a|

|===

=== Сотрудники

Идентификатор: `39FDE0C6-DB9F-495C-8125-79D82A98F193`
Псевдоним: `Employees`
Тип секции: `coll`
Название: _Сотрудники_

.Поля секции Сотрудники
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Файлы

Идентификатор: `DBCABE2B-59A1-46C8-BC77-76351A082A3B`
Псевдоним: `Files`
Тип секции: `coll`
Название: _Файлы_

.Поля секции Файлы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`File`
a|_Файл_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`


a|`Name`
a|_Имя файла_
a|`unistring`
a|
a|

a|`CurrentVersion`
a|_Текущая версия_
a|`int`
a|
a|

a|`CurrentVersionID`
a|_Идентификатор текущей версии_
a|`refid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`


a|`Index`
a|_Индекс_
a|`int`
a|
a|

a|`DocVerFileId`
a|_Идентификатор карточки версий в документе_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`


a|`ConsolidatedVerID`
a|_Идентификатор консолидированной версии_
a|`refid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`


|===

=== Лист согласования

Идентификатор: `83E3F4F9-465C-478C-816C-169D89B72859`
Псевдоним: `ReconciliationLog`
Тип секции: `coll`
Название: _Лист согласования_

.Поля секции Лист согласования
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Date`
a|_Дата_
a|`datetime`
a|
a|

a|`Result`
a|_Результат_
a|`enum`
a|
a|.Значения
* Не подписан = 3
* Согласован = 1
* Подписан = 2
* Ожидает согласования = 0
* Комментарий = 4
* Не согласован = 5
* Есть замечание = 6
* Без замечаний = 7


a|`File`
a|_Файл_
a|`refid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`
* Идентификатор секции: `DBCABE2B-59A1-46C8-BC77-76351A082A3B`


a|`FileVersionID`
a|_Версия файла_
a|`refid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`


a|`Comment`
a|_Замечание_
a|`unitext`
a|
a|

a|`RemarksFile`
a|_Файл замечаний_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`


a|`FileAttached`
a|_Прикреплен файл с комментариями_
a|`bool`
a|
a|

a|`ActualEmployee`
a|_Фактический сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`EmployeeText`
a|_Участник Текстовое_
a|`unistring`
a|
a|

a|`Decision`
a|_Решение_
a|`unitext`
a|
a|

a|`EventType`
a|_Тип события_
a|`int`
a|
a|

a|`Cycle`
a|_Номер цикла_
a|`int`
a|
a|

a|`StageName`
a|_Название этапа_
a|`string`
a|
a|

a|`BeginDate`
a|_Дата начала_
a|`datetime`
a|
a|

a|`EndDate`
a|_Дата завершения_
a|`datetime`
a|
a|

a|`DecisionSemantics`
a|_Код решения_
a|`int`
a|
a|

a|`Level`
a|_Идентификатор уровня_
a|`uniqueid`
a|
a|

a|`CommentFile`
a|_Файл с комментариями_
a|`fileid`
a|
a|

a|`TaskId`
a|_Ссылка на задание_
a|`refcardid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `20D21193-9F7F-4B62-8D69-272E78E1D6A8`


a|`StagePass`
a|_Проход этапа_
a|`int`
a|
a|

a|`DecisionType`
a|_Тип решения_
a|`int`
a|
a|

a|`StageInstanceId`
a|_Экземпляр этапа_
a|`refid`
a|
a|

a|`DecisionEmployeeText`
a|_Имена сотрудников решения_
a|`unitext`
a|
a|

a|`IsAdditional`
a|_Дополнительный участник_
a|`bool`
a|
a|

|===

=== Настройки

Идентификатор: `F0928D8C-1DB9-4B94-8E92-132FABC8709A`
Псевдоним: `Settings`
Тип секции: `struct`
Название: _Настройки_

.Поля секции Настройки
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ParticipantsCanEdit`
a|_Участники могут прикреплять новые версии файлов_
a|`bool`
a|
a|

a|`NeedRemarkToReject`
a|_Требовать замечание при отказе в согласовании_
a|`bool`
a|
a|

a|`CanAttachRemarksFiles`
a|_Участники могут прикреплять файлы замечаний_
a|`bool`
a|
a|

a|`FinishOnRejection`
a|_Завершать согласование при первом отказе_
a|`bool`
a|
a|

a|`Mode`
a|_Режим согласования_
a|`enum`
a|
a|.Значения
* Рецензирование = 0
* Согласование = 1
* Подписание = 2


a|`FinalDocumentStateID`
a|_Конечное состояние докумета_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`SettingsXML`
a|_Xml настроек_
a|`unitext`
a|
a|

a|`Period`
a|_Срок_
a|`int`
a|
a|

a|`UseHours`
a|_Использовать часы вместо дней_
a|`bool`
a|
a|

a|`Type`
a|_Тип_
a|`enum`
a|
a|.Значения
* Последовательно = 0
* Параллельно = 1


a|`AskOnSign`
a|_Спрашивать при добавлении электронной подписи_
a|`bool`
a|
a|

a|`StartWOShow`
a|_Начинать без показа карточки_
a|`bool`
a|
a|

a|`NextReconciliationTemplate`
a|_Шаблон следующего согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`


a|`StartBPOnFinish`
a|_Шаблон БП, запускаемого по окончании согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`


a|`StartReconcileWithoutFiles`
a|_Запускать согласование без файлов_
a|`bool`
a|
a|

|===

=== Таблица комментариев Инициатор

Идентификатор: `170323B1-803C-4FC5-A468-2F833EC61642`
Псевдоним: `CommentsTableInit`
Тип секции: `coll`
Название: _Таблица комментариев Инициатор_

.Поля секции Таблица комментариев Инициатор
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Date`
a|_Дата_
a|`datetime`
a|
a|

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`File`
a|_Файл замечаний_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`


a|`Comment`
a|_Комментарий_
a|`unitext`
a|
a|

|===

=== Таблица файлов для согласующего

Идентификатор: `71BD20E1-6B1A-4D95-8DB7-59982EA258F3`
Псевдоним: `FilesTable`
Тип секции: `coll`
Название: _Таблица файлов для согласующего_

.Поля секции Таблица файлов для согласующего
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Author`
a|_Автор версии_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`FileName`
a|_Имя файла_
a|`unistring`
a|
a|

a|`FileID`
a|_Идентификатор файла_
a|`refid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`
* Идентификатор секции: `DBCABE2B-59A1-46C8-BC77-76351A082A3B`


|===

=== Варианты завершения

Идентификатор: `AADFBCAF-11F3-4C4C-842C-22C9096A44C0`
Псевдоним: `FinishVariants`
Тип секции: `coll`
Название: _Варианты завершения_

.Поля секции Варианты завершения
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название результата_
a|`unistring`
a|
a|

a|`Value`
a|_Значение результата_
a|`int`
a|
a|

|===

=== Комментарии

Идентификатор: `933A78B3-25DB-4244-B0FE-A17D1E2B98EC`
Псевдоним: `Comments`
Тип секции: `coll`
Название: _Комментарии_

.Поля секции Комментарии
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`CommentAuthor`
a|_Автор комментария_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`CommentDate`
a|_Дата добавления комментария_
a|`datetime`
a|
a|

a|`CommentText`
a|_Текст комментария_
a|`unitext`
a|
a|

|===

=== Таблица маршуртов

Идентификатор: `4D88B4C4-A6DF-4942-9207-6E7B61D8E868`
Псевдоним: `PathTable`
Тип секции: `coll`
Название: _Таблица маршуртов_

.Поля секции Таблица маршуртов
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Path`
a|_Маршрут_
a|`refcardid`
a|
a|* Идентификатор типа: `6CA327B1-C44F-4751-82C0-17FB33747E46`


a|`RequirementDescription`
a|_Описание условия_
a|`unistring`
a|
a|

a|`SelectionRequirement`
a|_Условие выбора_
a|`unitext`
a|
a|

a|`Order`
a|_Приоритет_
a|`int`
a|
a|

|===

=== Лог передачи версий файлов между этапами

Идентификатор: `A7DC22BE-A86D-4D98-AAAF-16D9899DE459`
Псевдоним: `FileVersionsLog`
Тип секции: `coll`
Название: _Лог передачи версий файлов между этапами_

.Поля секции Лог передачи версий файлов между этапами
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Date`
a|_Дата_
a|`datetime`
a|
a|

a|`StageId`
a|_Идентификатор экземпляра этапа_
a|`refcardid`
a|
a|* Идентификатор типа: `0DB13C90-21B6-49D8-9070-8144DF97552A`


a|`Cycle`
a|_Номер цикла_
a|`int`
a|
a|

a|`Pass`
a|_Проход_
a|`int`
a|
a|

a|`FileCardId`
a|_Идентификатор карточки версионного файла_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`


a|`FileVersionId`
a|_Идентификатор версии файла_
a|`refid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`


a|`Type`
a|_Тип_
a|`enum`
a|
a|.Значения
* Неизвестная = 0
* Исходная версия цикла = 1
* Финальная версия цикла = 2
* Исходная версия этапа = 3
* Финальная версия этапа = 4
* Approver version = 5
* Версия в начале консолидации = 6
* Итоговая версия консолидации = 7


a|`ApproverId`
a|_Идентификатор согласующего_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`StageType`
a|_Тип этапа_
a|`int`
a|
a|

a|`TaskId`
a|_Идентификатор задания согласующего_
a|`refcardid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`


|===

=== Log

Идентификатор: `2962C755-1FF9-40ED-8B8C-385F70073223`
Псевдоним: `Log`
Тип секции: `coll`
Название: _Log_

.Поля секции Log
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Date`
a|_Дата_
a|`datetime`
a|
a|

a|`Message`
a|_Сообщение_
a|`unitext`
a|
a|

|===

