= Документ

Идентификатор: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`

Псевдоним: `CardDocument`

Название: _Документ_

== Секции карточки

=== Основная информация

Идентификатор: `30EB9B87-822B-4753-9A50-A1825DCA1B74`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Основная информация_

.Поля секции Основная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|480
a|

a|`Author`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
 >  > 

a|`VersioningType`
a|_Тип версий_
a|`enum`
a|
a|.Значения
* Нет = 0
* Авто = 1
* Ручной = 2
* Необходимо выбрать иное значение = 3


a|`CategoryList`
a|_Категории_
a|`refcardid`
a|
a|* Идентификатор типа: `337CC874-BF87-4C70-A29B-F099F630B9F2`


a|`RegDate`
a|_Дата регистрации_
a|`datetime`
a|
a|

a|`ExternalNumber`
a|_Исходящий номер_
a|`string`
a|
a|

a|`Content`
a|_Содержание_
a|`unitext`
a|
a|

a|`ReferenceList`
a|_Ссылки_
a|`refcardid`
a|
a|* Идентификатор типа: `C9B39BEF-1047-407B-9324-8EC00D64FBEE`
* Идентификатор секции: `568CE0A6-7096-43CC-9800-E0B268B14CC4`


a|`Tasks`
a|_Задания_
a|`refcardid`
a|
a|* Идентификатор типа: `4F34CC37-85AC-4D15-B694-2950E7F61055`


a|`SignatureList`
a|_Список подписей_
a|`refcardid`
a|
a|* Идентификатор типа: `CA25A38B-C65E-4A97-94EE-8E5067A6BECA`
* Идентификатор секции: `4A1AC881-DCBD-42C2-9C7A-E1DE7723400A`


a|`ResponsDepartment`
a|_Ответственное подразделение_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


a|`RegNumber`
a|_Регистрационный номер_
a|`refid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `61C8CC7C-35CE-49E5-9CCD-E9F3C1129445`


a|`Surveys`
a|_Опрос_
a|`refcardid`
a|
a|* Идентификатор типа: `A1D1A50B-8E1E-4116-A93A-684D95F50607`


a|`Registrar`
a|_Регистратор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`SenderStaffEmployee`
a|_Сотрудник отправитель_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`DeliveryDate`
a|_Дата от_
a|`datetime`
a|
a|

a|`AcquaintanceGroup`
a|_Группа ознакомления_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`SecurityId`
a|_Идентификатор грифа_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`RegistrationPlaceId`
a|_Идентификатор места регистрации_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`CaseId`
a|_Идентификатор дела_
a|`refid`
a|
a|

a|`DeliveryTypeId`
a|_Идентификатор типа доставки_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`NumberOfSheetsAppendix`
a|_Количество листов в приложении_
a|`int`
a|
a|

a|`NumberOfSheets`
a|_Количество листов в документе_
a|`int`
a|
a|

a|`RegNumberProvisional`
a|_Временный регистрационный номер_
a|`refid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `61C8CC7C-35CE-49E5-9CCD-E9F3C1129445`


a|`StatusId`
a|_Статус_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`TransferLog`
a|_Журнал передач_
a|`refcardid`
a|
a|

a|`ClerkId`
a|_Идентификатор делопроизводителя_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`WorkGroup`
a|_Рабочая группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`WasSent`
a|_Отправлен_
a|`bool`
a|
a|

a|`ItemID`
a|_Строка справочника_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

a|`HiddenReferenceList`
a|_Скрытые ссылки_
a|`refcardid`
a|
a|* Идентификатор типа: `C9B39BEF-1047-407B-9324-8EC00D64FBEE`
* Идентификатор секции: `568CE0A6-7096-43CC-9800-E0B268B14CC4`


|===

=== Системные свойства

Идентификатор: `91B2C5F7-9324-4CEF-9AFE-A457C8310F06`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`
Поля ссылки: 
Kind_Name

|===

=== Номера

Идентификатор: `61C8CC7C-35CE-49E5-9CCD-E9F3C1129445`
Псевдоним: `Numbers`
Тип секции: `coll`
Название: _Номера_

.Поля секции Номера
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`NumericPart`
a|_Числовая часть_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `D47F2C38-6553-4864-BAFF-0BC4D3A85290`


a|`Number`
a|_Номер_
a|`string`
a|
a|

|===

=== Бизнес-процессы

Идентификатор: `62094E68-24D2-4378-845D-284F76F0B679`
Псевдоним: `Processes`
Тип секции: `coll`
Название: _Бизнес-процессы_

.Поля секции Бизнес-процессы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ProcessId`
a|_Ссылка на процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`


a|`ProcessKind`
a|_Вид процесса_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `FF977158-5035-4494-AAD2-9FD0C708A7EC`


|===

=== Файлы

Идентификатор: `A6FA8BAF-2EA4-4071-AA3E-5C4E71646A90`
Псевдоним: `Files`
Тип секции: `coll`
Название: _Файлы_

.Поля секции Файлы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`FileId`
a|_Файл_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`
Поля ссылки: 
FileName > FileCurrentVersion

a|`FileType`
a|_Тип файла_
a|`enum`
a|
a|.Значения
* Основной = 0
* Дополнительный = 1


|===

=== Получатели

Идентификатор: `B6DFAEAD-BAAA-4024-908C-5DBD693D0FD3`
Псевдоним: `ReceiversStaff`
Тип секции: `coll`
Название: _Получатели_

.Поля секции Получатели
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ReceiverStaff`
a|_Получатель_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Согласующие

Идентификатор: `281A97FF-667F-46C8-8FBE-7CFC02EDFEDB`
Псевдоним: `Approvers`
Тип секции: `coll`
Название: _Согласующие_

.Поля секции Согласующие
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Approver`
a|_Согласующие_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Подписанты

Идентификатор: `D9F3BB4C-9C1A-464C-90F3-3D9657864709`
Псевдоним: `Signers`
Тип секции: `coll`
Название: _Подписанты_

.Поля секции Подписанты
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Signer`
a|_Подписано_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Отправитель контрагент

Идентификатор: `6E976D72-3EA7-4708-A2C2-2A1499141301`
Псевдоним: `SenderPartner`
Тип секции: `struct`
Название: _Отправитель контрагент_

.Поля секции Отправитель контрагент
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`SenderPerson`
a|_Сотрудник-отправитель_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `1A46BF0F-2D02-4AC9-8866-5ADF245921E8`


a|`SenderOrg`
a|_Организация-отправитель_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `C78ABDED-DB1C-4217-AE0D-51A400546923`


a|`SenderDep`
a|_Подразделение-отправитель_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `C78ABDED-DB1C-4217-AE0D-51A400546923`


a|`SignerPartnerId`
a|_Подписал-контрагент_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `1A46BF0F-2D02-4AC9-8866-5ADF245921E8`


|===

=== Получатели контрагенты

Идентификатор: `9E5F7CED-2D4A-44C0-8A23-14652E7B373F`
Псевдоним: `ReceiversPartners`
Тип секции: `coll`
Название: _Получатели контрагенты_

.Поля секции Получатели контрагенты
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ReceiverPartnerCo`
a|_Получатель-организация контрагента_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `C78ABDED-DB1C-4217-AE0D-51A400546923`


a|`ReceiverPartnersEmployee`
a|_Получатель сотрудник контрагента_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `1A46BF0F-2D02-4AC9-8866-5ADF245921E8`


a|`PartnerDeliveryTypeId`
a|_Идентификатор типа доставки_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


|===

=== Ознакомлены

Идентификатор: `AF798AE7-BAAC-486E-84EF-82C59DC00A7E`
Псевдоним: `AcquaintanceStaff`
Тип секции: `coll`
Название: _Ознакомлены_

.Поля секции Ознакомлены
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`AcquaintancePersons`
a|_На ознакомление_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Утверждено

Идентификатор: `F47D0D6B-07FE-4198-8F79-348AC55086E5`
Псевдоним: `ConfirmPersons`
Тип секции: `coll`
Название: _Утверждено_

.Поля секции Утверждено
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Confirm`
a|_Утвержден_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Договор

Идентификатор: `3997861D-4FF5-496A-B8A2-D16617DE91D7`
Псевдоним: `Contract`
Тип секции: `struct`
Название: _Договор_

.Поля секции Договор
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ContractDate`
a|_Дата заключения договора _
a|`datetime`
a|
a|

a|`ContractSum`
a|_Сумма договора_
a|`decimal`
a|
a|

a|`ContractCurrency`
a|_Валюта_
a|`enum`
a|
a|.Значения
* EUR = 0
* RUB = 1
* USD = 2
* JPY = 3
* CHF = 4
* GBP = 5
* AUD = 6
* AZN = 7
* AMD = 8
* BYR = 9
* BGN = 10
* BRL = 11
* HUF = 12
* DKK = 13
* INR = 14
* KZT = 15
* CAD = 16
* KGS = 17
* CNY = 18
* LVL = 19
* LTL = 20
* MDL = 21
* NOK = 22
* PLN = 23
* RON = 24
* XDR = 25
* SGD = 26
* TJS = 27
* TRY = 28
* TMT = 29
* UZS = 30
* UAH = 31
* CZK = 32
* SEK = 33
* ZAR = 34
* KRW = 35


a|`ContractKind`
a|_Вид договора_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`ContractSubject`
a|_Предмет договора _
a|`unitext`
a|
a|

a|`ContractBegin`
a|_Начало действия договора_
a|`datetime`
a|
a|

a|`ContractEnd`
a|_Завершение действия договора_
a|`datetime`
a|
a|

a|`ContractResponsible`
a|_Ответственный_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ContractNotes`
a|_Заметки_
a|`unitext`
a|
a|

a|`ActNumber`
a|_Номер акта_
a|`string`
a|
a|

a|`ActSigningDate`
a|_Дата подписания акта_
a|`datetime`
a|
a|

a|`AddAgreementDate`
a|_Дата подписания доп. Соглашения_
a|`datetime`
a|
a|

a|`AddAgreementNumber`
a|_Номер дополнительного соглашения_
a|`string`
a|
a|

a|`AttachmentNumber`
a|_Номер приложения_
a|`string`
a|
a|

a|`AttachmentDate`
a|_Дата подписания приложения_
a|`datetime`
a|
a|

a|`PartnerCompany`
a|_Организация контрагента_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `C78ABDED-DB1C-4217-AE0D-51A400546923`


a|`PartnerPerson`
a|_Контактное лицо контрагента_
a|`refid`
a|
a|* Идентификатор типа: `65FF9382-17DC-4E9F-8E93-84D6D3D8FE8C`
* Идентификатор секции: `1A46BF0F-2D02-4AC9-8866-5ADF245921E8`


a|`ContractRef`
a|_Договор_
a|`refcardid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `30EB9B87-822B-4753-9A50-A1825DCA1B74`


a|`ContractReconciliationDate`
a|_Дата согласования договора_
a|`datetime`
a|
a|

a|`ContractSigningDate`
a|_Дата подписания договора_
a|`datetime`
a|
a|

a|`PartnerReconciliationDate`
a|_Дата согласования контрагентом_
a|`datetime`
a|
a|

a|`PartnerSigningDate`
a|_Дата подписания контрагентом_
a|`datetime`
a|
a|

a|`ContractOriginalSigningDate`
a|_Дата подписания оригинала договора_
a|`datetime`
a|
a|

a|`ContractGroup`
a|_Группа договора_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`SumInRub`
a|_Сумма в рублях_
a|`float`
a|
a|

a|`FinishDate`
a|_Дата завершения_
a|`datetime`
a|
a|

|===

=== Лист согласования

Идентификатор: `2B1C18FF-FF96-40B5-B6EF-3A62D33BE4F1`
Псевдоним: `ReconciliationList`
Тип секции: `coll`
Название: _Лист согласования_

.Поля секции Лист согласования
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Position`
a|_Должность_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `CFDFE60A-21A8-4010-84E9-9D2DF348508C`


a|`Date`
a|_Дата согласования_
a|`datetime`
a|
a|

a|`Result`
a|_Результат_
a|`enum`
a|
a|.Значения
* Согласован = 0
* Не согласован = 1
* Подписан = 2
* Не подписан = 3
* Ожидает согласования = 4


a|`Sign`
a|_Подпись_
a|`unistring`
a|
a|

a|`Action`
a|_Действие_
a|`enum`
a|
a|.Значения
* Подписывает = 0
* Согласовывает = 1


a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ReconciliationId`
a|_Идентификатор согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`
* Идентификатор секции: `35473281-BCEB-415A-8603-74549421037E`


a|`ActualEmployee`
a|_Фактический участник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`EmployeeText`
a|_Участник Текстовое_
a|`unistring`
a|
a|

a|`StageName`
a|_Название этапа_
a|`unistring`
a|
a|

a|`DecisionText`
a|_Текст решения_
a|`unistring`
a|
a|

a|`Comment`
a|_Замечание_
a|`unitext`
a|
a|

|===

=== Согласование

Идентификатор: `E3E14386-27A4-4D24-96CE-9907CDCC438B`
Псевдоним: `Reconciliation`
Тип секции: `struct`
Название: _Согласование_

.Поля секции Согласование
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Reconciliation`
a|_Активное согласование_
a|`refcardid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`
* Идентификатор секции: `35473281-BCEB-415A-8603-74549421037E`


a|`ReconciliationState`
a|_Состояние активного согласования_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`ReconciliationRoute`
a|_Маршрут согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `99DD6295-1B3D-4DA6-8256-8332D3E955C9`
* Идентификатор секции: `25B976F7-1C74-4D5C-B60A-7A8F4897A8CE`


a|`ReconciliationLog`
a|_Ход согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `24410C2C-3757-4E0D-839C-D86C2B2DAD66`
* Идентификатор секции: `30C984A9-A9C0-45E4-95D6-9D5FC22F389C`


|===

=== Комментарии

Идентификатор: `712EFABE-F62E-4304-9472-F1940F66CCEE`
Псевдоним: `Comments`
Тип секции: `coll`
Название: _Комментарии_

.Поля секции Комментарии
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`CommentAuthor`
a|_Автор комментария_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`CommentDate`
a|_Дата время комментария_
a|`datetime`
a|
a|

a|`CommentText`
a|_Текст комментария_
a|`unitext`
a|
a|

|===

=== Контроль

Идентификатор: `D5C373AD-8008-446E-B2D6-DB96ACE455C4`
Псевдоним: `Control`
Тип секции: `struct`
Название: _Контроль_

.Поля секции Контроль
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ControlTypeId`
a|_Идентификатор контроля_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`ControlDate`
a|_Дата контроля_
a|`datetime`
a|
a|

a|`StopControlDate`
a|_Дата снятия с контроля_
a|`datetime`
a|
a|

a|`DocumentInspectorId`
a|_Идентификатор контролер _
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`StopControlPersonId`
a|_Сотрудник снявший с контроля_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Адресаты

Идентификатор: `3D2CC27A-DAF4-4C83-AA3D-2FFB4C007984`
Псевдоним: `Addressees`
Тип секции: `coll`
Название: _Адресаты_

.Поля секции Адресаты
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`EmployeeId`
a|_Идентификатор сотрудника_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`DepartmentId`
a|_Идентификатор подразделения/организации_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


|===

