= Маршрут согласования (устарел)

Идентификатор: `99DD6295-1B3D-4DA6-8256-8332D3E955C9`

Псевдоним: `CardReconcilePath`

Название: _Маршрут согласования (устарел)_

== Секции карточки

=== Системные свойства

Идентификатор: `D96941F5-E1D4-4E5E-907C-47B018C9D8EB`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Номера

Идентификатор: `79DB0422-1EA4-47B8-A4E7-E317C22039B8`
Псевдоним: `Numbers`
Тип секции: `coll`
Название: _Номера_

.Поля секции Номера
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`NumericPart`
a|_Числовая часть_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `D47F2C38-6553-4864-BAFF-0BC4D3A85290`


a|`Number`
a|_Полный номер_
a|`string`
a|
a|

|===

=== Бизнес-процессы

Идентификатор: `0429F4EE-E08F-432D-A1F1-9C9F39ADBE7B`
Псевдоним: `Processes`
Тип секции: `coll`
Название: _Бизнес-процессы_

.Поля секции Бизнес-процессы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ProcessID`
a|_Бизнес-процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`
Поля ссылки: 
Process_Name > Process_State

a|`ProcessKind`
a|_Вид процесса_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `FF977158-5035-4494-AAD2-9FD0C708A7EC`


|===

=== ReconcileOrderTable

Идентификатор: `20C01E7C-0820-4B14-BBD9-A9B6E14C196B`
Псевдоним: `ReconcileOrderTable`
Тип секции: `coll`
Название: _ReconcileOrderTable_

.Поля секции ReconcileOrderTable
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Order`
a|_Порядок_
a|`int`
a|
a|

a|`Condition1`
a|_Условие 1_
a|`unitext`
a|
a|

a|`Condition2`
a|_Условие 2_
a|`unitext`
a|
a|

a|`StageCard`
a|_Этап_
a|`refcardid`
a|
a|* Идентификатор типа: `35E7139A-82B8-425D-AB14-ADC2DB757D7A`


a|`ReconcileType`
a|_Тип согласования_
a|`enum`
a|
a|.Значения
* Sequential = 0
* Parallel = 1
* Consolidation = 2
* Registration = 3


a|`ReconcilerType`
a|_Тип согласующего_
a|`enum`
a|
a|.Значения
* Сотрудник = 0
* Группа = 1
* Роль = 2
* Руководитель инициатора = 3
* Все руководители инициатора = 4
* Руководитель инициатора на уровне = 5
* Инициатор = 6
* Регистратор = 7


a|`ParticipantAlias`
a|_Псевдоним участника_
a|`unitext`
a|
a|

|===

=== MainInfo

Идентификатор: `25B976F7-1C74-4D5C-B60A-7A8F4897A8CE`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _MainInfo_

.Поля секции MainInfo
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unitext`
a|
a|

a|`Author`
a|_Автор_
a|`unitext`
a|
a|

a|`RegisteredBy`
a|_Регистратор_
a|`unitext`
a|
a|

a|`BusinessProcessFolder`
a|_Папка экземпляров БП_
a|`refid`
a|
a|* Идентификатор типа: `DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2`
* Идентификатор секции: `FE27631D-EEEA-4E2E-A04C-D4351282FB55`


a|`ReconcileProjectsFolder`
a|_Папка проектов на согласовании_
a|`refid`
a|
a|* Идентификатор типа: `DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2`
* Идентификатор секции: `FE27631D-EEEA-4E2E-A04C-D4351282FB55`


a|`RegistrationFolder`
a|_Папка регистрации_
a|`refid`
a|
a|* Идентификатор типа: `DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2`
* Идентификатор секции: `FE27631D-EEEA-4E2E-A04C-D4351282FB55`


a|`RejectFolder`
a|_Папка при отзыве_
a|`refid`
a|
a|* Идентификатор типа: `DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2`
* Идентификатор секции: `FE27631D-EEEA-4E2E-A04C-D4351282FB55`


a|`ProjectsFolder`
a|_Название папки проектов_
a|`unitext`
a|
a|

a|`RegistrationNumerator`
a|_Регистрационный нумератор_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `A4FE6E8E-7DD7-45B4-AC4E-3C74F0B6369A`


a|`FinishBusinessProcess`
a|_Запуск процесса при завершении_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`


a|`RejectBusinessProcess`
a|_Запуск процесса при отклонении_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`


a|`FinalState`
a|_Финальное состояние_
a|`unitext`
a|
a|

a|`SkipRepeatApprove`
a|_Пропускать повторное согласование_
a|`bool`
a|
a|

a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


|===

