= Карточка журнала уведомлений

Идентификатор: `5DB6F274-D8A7-4580-8B28-3C9B1D5F1CBD`

Псевдоним: `CardNotificationLog`

Название: _Карточка журнала уведомлений_

== Секции карточки

=== Основная информация

Идентификатор: `E78B636E-0793-4025-B26F-7EFA3B5B4116`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Основная информация_

.Поля секции Основная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Day`
a|_День_
a|`datetime`
a|
a|

|===

=== Журнал

Идентификатор: `E4E82605-9379-42BB-8008-3B40E3410AF9`
Псевдоним: `Log`
Тип секции: `coll`
Название: _Журнал_

.Поля секции Журнал
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Date`
a|_Дата_
a|`datetime`
a|
a|

a|`RecipientId`
a|_Получатель_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`RecipientAddress`
a|_Адрес получателя_
a|`unistring`
a|256
a|

a|`SenderAddress`
a|_Адрес отправителя_
a|`unistring`
a|256
a|

a|`Subject`
a|_Тема сообщения_
a|`unistring`
a|4096
a|

a|`Body`
a|_Тело сообщения_
a|`unitext`
a|
a|

a|`Status`
a|_Статус_
a|`int`
a|
a|

a|`ErrorMessage`
a|_Сообщение об ошибке_
a|`unitext`
a|
a|

a|`NotificationSourceCardId`
a|_Карточка - источник уведомления_
a|`refcardid`
a|
a|

a|`NotificationDestCardId`
a|_Карточка, о которой уведомления_
a|`refcardid`
a|
a|

|===

