= Список файлов

Идентификатор: `BFC9D190-BCD6-411A-B9F9-3160D3F68819`

Псевдоним: `FileList`

Название: _Список файлов_

== Секции карточки

=== Ссылки на файлы

Идентификатор: `E962AC85-0F53-4439-A1CD-171E46C3EF91`
Псевдоним: `FileReferences`
Тип секции: `coll`
Название: _Ссылки на файлы_

.Поля секции Ссылки на файлы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`CardFileID`
a|_Карточка файла_
a|`refcardid`
a|
a|* Идентификатор типа: `2BBD0A41-265E-4FF8-82D6-C6342F34B1AF`
* Идентификатор секции: `B4562DF8-AF19-4D0F-85CA-53A311354D39`
Поля ссылки: 
 >  >  >  > 

a|`CanModify`
a|_Разрешено изменение_
a|`bool`
a|
a|

a|`CanCheckout`
a|_Разрешено блокирование_
a|`bool`
a|
a|

a|`CanDelete`
a|_Разрешено удаление_
a|`bool`
a|
a|

a|`CommentRequired`
a|_Необходим комментарий_
a|`bool`
a|
a|

a|`ResultFolder`
a|_Папка результирующего документа_
a|`refid`
a|
a|* Идентификатор типа: `DA86FABF-4DD7-4A86-B6FF-C58C24D12DE2`
* Идентификатор секции: `FE27631D-EEEA-4E2E-A04C-D4351282FB55`


a|`FieldsToFile`
a|_Копировать поля в свойства файла_
a|`bool`
a|
a|

a|`FileToFields`
a|_Копировать свойства файла в поля_
a|`bool`
a|
a|

a|`IsNew`
a|_Новый файл_
a|`bool`
a|
a|

a|`IsDeleted`
a|_Файл удален_
a|`bool`
a|
a|

a|`OpenFileWithCard`
a|_Открывать файл_
a|`bool`
a|
a|

|===

=== Основная информация

Идентификатор: `3F8270DB-3603-463C-BA59-26B89EBB6CB5`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Основная информация_

.Поля секции Основная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Count`
a|_Количество файлов_
a|`int`
a|
a|

|===

