= Карточка строки справочника

Идентификатор: `E898C387-0162-4F37-A93C-13BAA07FF183`

Псевдоним: `CardBaseUniversalItem`

Название: _Карточка строки справочника_

== Секции карточки

=== Основная информация

Идентификатор: `F5641A7E-83AF-4C20-9C60-EA2973C4F135`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Основная информация_

.Поля секции Основная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Item`
a|_Ссылка_
a|`refid`
a|
a|

a|`State`
a|_State_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

|===

=== Системные свойства

Идентификатор: `0345F68C-9E2D-4675-B22D-DFC67DF94333`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

