= Этап согласования (устарел)

Идентификатор: `35E7139A-82B8-425D-AB14-ADC2DB757D7A`

Псевдоним: `CardReconcileStage`

Название: _Этап согласования (устарел)_

== Секции карточки

=== Системные свойства

Идентификатор: `15AD3DC7-2216-42F1-844D-5823A540C553`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Номера

Идентификатор: `543B2C97-42F3-480A-AA05-9C2D5A2AFCEC`
Псевдоним: `Numbers`
Тип секции: `coll`
Название: _Номера_

.Поля секции Номера
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`NumericPart`
a|_Числовая часть_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `D47F2C38-6553-4864-BAFF-0BC4D3A85290`


a|`Number`
a|_Полный номер_
a|`string`
a|
a|

|===

=== Бизнес-процессы

Идентификатор: `8B4B9D55-E1BA-41D8-B9B1-7E9B3097DF08`
Псевдоним: `Processes`
Тип секции: `coll`
Название: _Бизнес-процессы_

.Поля секции Бизнес-процессы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ProcessID`
a|_Бизнес-процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`
Поля ссылки: 
Process_Name > Process_State

a|`ProcessKind`
a|_Вид процесса_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `FF977158-5035-4494-AAD2-9FD0C708A7EC`


|===

=== MainInfo

Идентификатор: `381CB937-019E-4413-A2BD-646BE7F7250E`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _MainInfo_

.Поля секции MainInfo
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название этапа_
a|`unitext`
a|
a|

a|`Order`
a|_Порядок_
a|`int`
a|
a|

a|`StateName`
a|_Название состояния этапа_
a|`unitext`
a|
a|

a|`RejectedStateName`
a|_Название состояния при отклонении_
a|`unitext`
a|
a|

a|`ParticipantAlias`
a|_Псевдоним участника_
a|`unitext`
a|
a|

a|`ReconcileType`
a|_Тип согласования_
a|`enum`
a|
a|.Значения
* Последовательное = 0
* Параллельное = 1
* Консолидация = 2
* Регистрация = 3


a|`Decision`
a|_Решения_
a|`unitext`
a|
a|

a|`ReconcilerType`
a|_Тип согласующего_
a|`enum`
a|
a|.Значения
* Сотрудник = 0
* Группа = 1
* Роль = 2
* Руководитель инициатора = 3
* Все руководители инициатора = 4
* Руководитель инициатора на уровне = 5
* Инициатор = 6
* Регистратор = 7


a|`HierarchyLevel`
a|_Уровень иерархии_
a|`int`
a|
a|

a|`TotalDuration`
a|_Общая длительность_
a|`bool`
a|
a|

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Group`
a|_Группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`Role`
a|_Роль_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `F6927A03-5BCE-4C7E-9C8F-E61C6D9F256E`


a|`Duration`
a|_Длительность_
a|`int`
a|
a|

a|`DurationProperty`
a|_Свойство длительности_
a|`unitext`
a|
a|

a|`BindedField`
a|_Связанное поле_
a|`enum`
a|
a|.Значения
* Author = 0
* Registrar = 1
* SenderStaffEmplyee = 2
* ReceiverStaff = 3
* Approver = 4
* Signer = 5
* Свойство = 6
* <не задано> = 7


a|`PropertyName`
a|_Название свойства_
a|`unitext`
a|
a|

a|`TaskKindName`
a|_Название вида задания_
a|`unitext`
a|
a|

a|`PrintTemplateName`
a|_Название шаблона печати_
a|`unitext`
a|
a|

a|`BusinessCalendar`
a|_Бизнес-календарь_
a|`refcardid`
a|
a|* Идентификатор типа: `F31B9F60-F81F-4825-8216-FC3C1FF15222`


a|`BusinessProcess`
a|_Бизнес-процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`


a|`ChangeReconcileDoc`
a|_Разрешено изменение согласуемых документов_
a|`bool`
a|
a|

a|`ReturnReadOnly`
a|_Возвращать права в Только для чтения_
a|`bool`
a|
a|

a|`ChangeCard`
a|_Разрешить изменение карточки_
a|`bool`
a|
a|

a|`UpdateFilesList`
a|_Обновлять список файлов_
a|`bool`
a|
a|

a|`AddFiles`
a|_Добавлять файлы в карточку_
a|`bool`
a|
a|

a|`AltExecution`
a|_Альтернативное исполнение_
a|`bool`
a|
a|

a|`AsyncExecution`
a|_Асинхронное исполнение_
a|`bool`
a|
a|

a|`UseWithPrev`
a|_Использовать с предыдущим_
a|`bool`
a|
a|

a|`IgnoreNegative`
a|_Игнорировать отрицательное решение_
a|`bool`
a|
a|

a|`HideDefaults`
a|_Скрыть стандартные кнопки_
a|`bool`
a|
a|

a|`OnlyPreview`
a|_Только ознакомление_
a|`bool`
a|
a|

a|`AutoRegistration`
a|_Автоматическая регистрация_
a|`bool`
a|
a|

a|`NotAddToAL`
a|_Не добавлять в ЛС_
a|`bool`
a|
a|

a|`AdResulToAL`
a|_Добавление в ЛС результатов ПЗ_
a|`bool`
a|
a|

a|`WaitMode`
a|_Режим ожидания_
a|`bool`
a|
a|

a|`TaskContent`
a|_Содержание задания_
a|`unitext`
a|
a|

a|`TaskCompletionOption`
a|_Вариант завершения задания_
a|`refid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `40FF71AF-8A8B-41DF-8F60-4DA6C6790DAE`


a|`TaskSignatureLabel`
a|_Метка для подписи задания_
a|`refid`
a|
a|* Идентификатор типа: `97B7BB8D-751D-4A58-87F1-4135D771C7EA`
* Идентификатор секции: `0617ED64-4F47-46A0-9D25-6B03929C3B4A`


a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

|===

