= Задание

Идентификатор: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`

Псевдоним: `CardTask`

Название: _Задание_

== Секции карточки

=== Задание

Идентификатор: `20D21193-9F7F-4B62-8D69-272E78E1D6A8`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Задание_

.Поля секции Задание
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|480
a|

a|`Content`
a|_Содержание_
a|`unitext`
a|
a|

a|`Author`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`StartDate`
a|_Дата начала плановая_
a|`datetime`
a|
a|

a|`EndDate`
a|_Дата завершения плановая_
a|`datetime`
a|
a|

a|`StartDateActual`
a|_Дата начала фактическая_
a|`datetime`
a|
a|

a|`EndDateActual`
a|_Дата завершения фактическая_
a|`datetime`
a|
a|

a|`Laboriousness`
a|_Трудоемкость плановая (ч)_
a|`int`
a|
a|

a|`LaboriousnessActual`
a|_Трудоемкость фактическая (ч)_
a|`int`
a|
a|

a|`Reminder`
a|_Напомнить за N часов до срока завершения задания._
a|`int`
a|
a|

a|`ReminderDate`
a|_Дата напоминания_
a|`datetime`
a|
a|

a|`ForManager`
a|_Лично руководителю_
a|`bool`
a|
a|

a|`ParentTask`
a|_Родительское задание_
a|`refcardid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `20D21193-9F7F-4B62-8D69-272E78E1D6A8`


a|`Delegate`
a|_Делегат_
a|`refid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `2BD2883D-0FBE-47F3-A24B-D5489466765A`


a|`ChildTaskList`
a|_Список подчинённых заданий_
a|`refcardid`
a|
a|* Идентификатор типа: `4F34CC37-85AC-4D15-B694-2950E7F61055`


a|`ReferenceList`
a|_Список ссылок_
a|`refcardid`
a|
a|* Идентификатор типа: `C9B39BEF-1047-407B-9324-8EC00D64FBEE`


a|`SignatureList`
a|_Список подписей_
a|`refcardid`
a|
a|* Идентификатор типа: `CA25A38B-C65E-4A97-94EE-8E5067A6BECA`
* Идентификатор секции: `4A1AC881-DCBD-42C2-9C7A-E1DE7723400A`


a|`CompletedUser`
a|_Сотрудник, завершивший задание. _
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`RejectedUser`
a|_Сотрудник, отклонивший задание. _
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Report`
a|_Отчет_
a|`unitext`
a|
a|

a|`IsOverdue`
a|_Завершено позже срока_
a|`bool`
a|
a|

a|`PercentCompleted`
a|_Процент завершения (%)_
a|`int`
a|
a|

a|`DurationActual`
a|_Длительность фактическая (ч)_
a|`int`
a|
a|

a|`OnControl`
a|_На контроле_
a|`bool`
a|
a|

a|`Controller`
a|_Контролер хода исполнения задания_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ControlDate`
a|_Дата контроля_
a|`datetime`
a|
a|

a|`RequiresAcceptance`
a|_Требуется приёмка_
a|`bool`
a|
a|

a|`ExecutionStopped`
a|_Прекращено исполнение_
a|`bool`
a|
a|

a|`StartDateBeforePostponement`
a|_Дата начала плановая до переносов_
a|`datetime`
a|
a|

a|`EndDateBeforePostponement`
a|_Дата завершения плановая до переносов_
a|`datetime`
a|
a|

a|`PostponementCount`
a|_Количество переносов сроков исполнения_
a|`int`
a|
a|

a|`Priority`
a|_Важность_
a|`enum`
a|
a|.Значения
* Низкая = 0
* Нормальная = 1
* Высокая = 2


a|`StartTaskDate`
a|_Дата отправки задания_
a|`datetime`
a|
a|

a|`OutlookTask`
a|_Задание MS Outlook_
a|`unistring`
a|256
a|

a|`CreateMessages`
a|_Сформировать сообщения для задания_
a|`bool`
a|
a|

a|`Number`
a|_Номер_
a|`refid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `F8008032-E07B-467D-809F-DE0EACC92E29`


a|`ResponsibleTaskId`
a|_Задание ответственного исполнителя_
a|`refcardid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `20D21193-9F7F-4B62-8D69-272E78E1D6A8`


a|`ResponsibleTaskPerformerId`
a|_Ответственный исполнитель_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`CompletionResult`
a|_Результат завершения задания_
a|`refid`
a|
a|* Идентификатор типа: `C7B36F33-CDD4-4DA9-8444-600FE14111E4`
* Идентификатор секции: `40FF71AF-8A8B-41DF-8F60-4DA6C6790DAE`


a|`AdditionalFileList`
a|_Список дополнительных файлов_
a|`refcardid`
a|
a|* Идентификатор типа: `065E13F8-4E13-4E47-9E2A-A5F86E6439AA`


a|`ReadOnlyFileList`
a|_Список файлов только для чтения_
a|`refcardid`
a|
a|* Идентификатор типа: `065E13F8-4E13-4E47-9E2A-A5F86E6439AA`


a|`ReconcileFileList`
a|_Список файлов на согласование_
a|`refcardid`
a|
a|* Идентификатор типа: `065E13F8-4E13-4E47-9E2A-A5F86E6439AA`


a|`KindControl`
a|_Вид контроля_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`RequestedEndDate`
a|_Запрошенный срок_
a|`datetime`
a|
a|

a|`WorkGroup`
a|_Рабочая группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`CancelDelegationUser`
a|_Сотрудник, отменивший делегирование_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`MessagesId`
a|_Карточка сообщений_
a|`refcardid`
a|
a|* Идентификатор типа: `23A98E72-8C75-4B99-A3E6-3DA5853B3CA9`


a|`Order`
a|_Порядок задания в группе_
a|`int`
a|
a|

a|`CreatedByTrigger`
a|_Создано триггером_
a|`bool`
a|
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`ApprovalVersion`
a|_Версия согласования_
a|`enum`
a|
a|.Значения
* Обычная = 0
* Усовершенствованная = 1


a|`ParentDocument`
a|_Родительский документ_
a|`refcardid`
a|
a|* Идентификатор типа: `B9F7BFD7-7429-455E-A3F1-94FFB569C794`
* Идентификатор секции: `30EB9B87-822B-4753-9A50-A1825DCA1B74`


|===

=== Выбранные исполнители

Идентификатор: `5149E42F-FD41-458F-93D9-D00F4A105E9C`
Псевдоним: `SelectedPerformers`
Тип секции: `coll`
Название: _Выбранные исполнители_

.Поля секции Выбранные исполнители
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Unit`
a|_Подразделение_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


a|`Group`
a|_Группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`StaffRole`
a|_Роль_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `F6927A03-5BCE-4C7E-9C8F-E61C6D9F256E`


a|`SearchWord`
a|_Поисковое слово_
a|`uniqueid`
a|
a|

|===

=== Назначенные исполнители

Идентификатор: `80C8F976-1F0D-4B67-82D2-A59230ECADE7`
Псевдоним: `Performers`
Тип секции: `coll`
Название: _Назначенные исполнители_

.Поля секции Назначенные исполнители
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
EmployeeDisplayString

|===

=== Системные свойства

Идентификатор: `CAC73A35-ABAF-4A57-A7A9-C2006F1C14BC`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Номера

Идентификатор: `F8008032-E07B-467D-809F-DE0EACC92E29`
Псевдоним: `Numbers`
Тип секции: `coll`
Название: _Номера_

.Поля секции Номера
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`NumericPart`
a|_Числовая часть_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `D47F2C38-6553-4864-BAFF-0BC4D3A85290`


a|`Number`
a|_Номер_
a|`string`
a|
a|

|===

=== Бизнес-процессы

Идентификатор: `3A4614CC-9C46-47D2-9D38-C4A6E42D945B`
Псевдоним: `Processes`
Тип секции: `coll`
Название: _Бизнес-процессы_

.Поля секции Бизнес-процессы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ProcessId`
a|_Ссылка на процесс_
a|`refcardid`
a|
a|* Идентификатор типа: `AE82DD57-348C-4407-A50A-9F2C7D694DA8`
* Идентификатор секции: `0EF6BCCA-7A09-4027-A3A2-D2EEECA1BF4D`


a|`ProcessKind`
a|_Вид процесса_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `FF977158-5035-4494-AAD2-9FD0C708A7EC`


|===

=== Текущие исполнители

Идентификатор: `134EA363-F5A8-4B80-B302-B21C954CE983`
Псевдоним: `CurrentPerformers`
Тип секции: `coll`
Название: _Текущие исполнители_

.Поля секции Текущие исполнители
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
EmployeeDisplayString

|===

=== Список делегирования

Идентификатор: `2BD2883D-0FBE-47F3-A24B-D5489466765A`
Псевдоним: `Delegates`
Тип секции: `tree`
Название: _Список делегирования_

.Поля секции Список делегирования
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Return`
a|_Признак возврата с делегирования_
a|`bool`
a|
a|

a|`Returned`
a|_Возвращено_
a|`bool`
a|
a|

a|`Performer`
a|_Исполнитель_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
EmployeeDisplayString

a|`Date`
a|_Время выполнения делегирования_
a|`datetime`
a|
a|

a|`Comment`
a|_Комментарий при выполнений делегирования_
a|`unistring`
a|2048
a|

a|`Reason`
a|_Причина делегирования_
a|`enum`
a|
a|.Значения
* Исполнитель не активен = 0
* Автоматически = 1
* Делегирование = 2


a|`DelegatedEmployee`
a|_Сотрудник, выполнивший делегирование_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ReturnDate`
a|_Дата возврата с делегирования_
a|`datetime`
a|
a|

|===

=== Исполнители

Идентификатор: `02BB0DB2-F0D2-4280-91F9-FE532E3FBE1F`
Псевдоним: `DelegatedPerformers`
Тип секции: `coll`
Название: _Исполнители_

.Поля секции Исполнители
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
EmployeeDisplayString

|===

=== Кому делегировано

Идентификатор: `D3A43C3F-5EBB-4802-BB6B-58CA2717EA2F`
Псевдоним: `DelegatedTo`
Тип секции: `coll`
Название: _Кому делегировано_

.Поля секции Кому делегировано
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
EmployeeDisplayString

|===

=== Актуальные делегаты

Идентификатор: `27322A99-5272-422A-9376-F3557589C6F5`
Псевдоним: `ActualDelegates`
Тип секции: `coll`
Название: _Актуальные делегаты_

.Поля секции Актуальные делегаты
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`
Поля ссылки: 
EmployeeDisplayString

|===

=== Комментарии

Идентификатор: `3CD88465-02FA-4CE1-883F-DD6E099FE1CC`
Псевдоним: `Comments`
Тип секции: `coll`
Название: _Комментарии_

.Поля секции Комментарии
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Author`
a|_Автор комментария_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`CreationDate`
a|_Дата создания_
a|`datetime`
a|
a|

a|`Content`
a|_Содержание_
a|`unitext`
a|
a|

|===

=== Настройки

Идентификатор: `629161CD-F970-4538-BC07-F56CDB937B3D`
Псевдоним: `Presets`
Тип секции: `struct`
Название: _Настройки_

.Поля секции Настройки
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`AllowDelegateToAnyEmployee`
a|_Разрешено делегирование вручную любому сотруднику_
a|`bool`
a|
a|

a|`AllowDelegateToEmployeeFromList`
a|_Разрешено делегирование вручную сотруднику из списка_
a|`bool`
a|
a|

a|`RequestCommentAtTaskRejection`
a|_Запрашивать комментарий при отклонении задания_
a|`bool`
a|
a|

a|`UseBusinessCalendar`
a|_Использовать бизнес-календарь_
a|`bool`
a|
a|

a|`AllowDelegateManual`
a|_Разрешено делегировать вручную_
a|`bool`
a|
a|

a|`DelegateToDeputy`
a|_Разрешить делегирование заместителю при неактивности исполнителя_
a|`bool`
a|
a|

a|`Initialized`
a|_Инициализированы_
a|`bool`
a|
a|

|===

=== Настройка исполнителей

Идентификатор: `8A7520F9-032F-4A6C-850A-AB02FCAB5B1E`
Псевдоним: `DelegationPresets`
Тип секции: `coll`
Название: _Настройка исполнителей_

.Поля секции Настройка исполнителей
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Unit`
a|_Подразделение_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


a|`Group`
a|_Группа_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `5B607FFC-7EA2-47B1-90D4-BB72A0FE7280`


a|`Role`
a|_Роль_
a|`refid`
a|
a|* Идентификатор типа: `7984F2CE-9345-4C59-B66B-7125DD9195A1`
* Идентификатор секции: `1C088782-C467-4FB0-B988-D5C5235500A1`


a|`SearchWord`
a|_Поисковое слово_
a|`uniqueid`
a|
a|

|===

=== Настройка основных типов ссылок

Идентификатор: `B2774BC9-0D16-41DE-BAFB-4C0C8E211400`
Псевдоним: `MainLinkTypePresets`
Тип секции: `coll`
Название: _Настройка основных типов ссылок_

.Поля секции Настройка основных типов ссылок
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`LinkType`
a|_Тип ссылки_
a|`refid`
a|
a|* Идентификатор типа: `38165FA6-FA69-4261-9EC3-675FEBB89C8B`
* Идентификатор секции: `5C103E40-BA13-44EF-A628-E6286DC687D6`


a|`CopyLink`
a|_Копировать ссылку_
a|`bool`
a|
a|

|===

=== Настройка дополнительных типов ссылок

Идентификатор: `0FC371AC-F9ED-4E72-A799-AC42677D8452`
Псевдоним: `AttachmentLinkTypePresets`
Тип секции: `coll`
Название: _Настройка дополнительных типов ссылок_

.Поля секции Настройка дополнительных типов ссылок
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`LinkType`
a|_Тип ссылки_
a|`refid`
a|
a|* Идентификатор типа: `38165FA6-FA69-4261-9EC3-675FEBB89C8B`
* Идентификатор секции: `5C103E40-BA13-44EF-A628-E6286DC687D6`


a|`CopyLink`
a|_Копировать ссылку_
a|`bool`
a|
a|

|===

=== Настройка типов ссылок отчётов

Идентификатор: `3B665B87-3D00-4D8D-90E9-55613BFDEF69`
Псевдоним: `ReportLinkTypePresets`
Тип секции: `coll`
Название: _Настройка типов ссылок отчётов_

.Поля секции Настройка типов ссылок отчётов
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`LinkType`
a|_Тип ссылки_
a|`refid`
a|
a|* Идентификатор типа: `38165FA6-FA69-4261-9EC3-675FEBB89C8B`
* Идентификатор секции: `5C103E40-BA13-44EF-A628-E6286DC687D6`


a|`CopyLink`
a|_Копировать ссылку_
a|`bool`
a|
a|

|===

=== Настройки копирования

Идентификатор: `3B80B946-72B8-491E-B664-8D6E9483C136`
Псевдоним: `ChildCopyFieldsPresets`
Тип секции: `coll`
Название: _Настройки копирования_

.Поля секции Настройки копирования
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`SectionPath`
a|_Путь к секции_
a|`unistring`
a|
a|

a|`FieldAlias`
a|_Псевдоним поля_
a|`unistring`
a|
a|

a|`SectionName`
a|_Название секции_
a|`unistring`
a|
a|

a|`FieldName`
a|_Название поля_
a|`unistring`
a|
a|

a|`FieldId`
a|_Идентификатор поля_
a|`uniqueid`
a|
a|

|===

=== Настройки завершения

Идентификатор: `04848EB8-B298-4F15-8EBB-A9DCE3D22CA1`
Псевдоним: `CompletionPresets`
Тип секции: `struct`
Название: _Настройки завершения_

.Поля секции Настройки завершения
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ReportFileRequired`
a|_Запрашивать файл отчёта_
a|`bool`
a|
a|

a|`AutoCompletionType`
a|_Вид автоматического завершения_
a|`enum`
a|
a|.Значения
* Не завершать = 0
* При завершении всех подчинённых = 1
* При завершении любого из подчинённых = 2


a|`CompleteChildren`
a|_Завершать подчинённые_
a|`bool`
a|
a|

a|`DependingOnRelatedTasksCompletionType`
a|_Вид завершения, при незавершённых связанных заданиях_
a|`enum`
a|
a|.Значения
* Не завершать = 0
* Завершать = 1
* На усмотрение пользователя = 2


a|`ReportRequired`
a|_Ввести отчет_
a|`bool`
a|
a|

a|`CompleteChildrenTaskGroups`
a|_Завершать подчинённые группы заданий_
a|`bool`
a|
a|

a|`RecallChildrenMode`
a|_Поведение подчинённых заданий при отзыве_
a|`enum`
a|
a|.Значения
* Не менять = 0
* Отозвать = 1
* Удалить = 2


a|`RecallChildrenTaskGroupsMode`
a|_Поведение подчинённых групп заданий при отзыве_
a|`enum`
a|
a|.Значения
* Не менять = 0
* Отозвать = 1
* Удалить = 2


|===

=== Варианты завершения 

Идентификатор: `40FF71AF-8A8B-41DF-8F60-4DA6C6790DAE`
Псевдоним: `CompletionOptions`
Тип секции: `coll`
Название: _Варианты завершения _

.Поля секции Варианты завершения 
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`IconFileId`
a|_Иконка_
a|`fileid`
a|
a|

a|`Name`
a|_Название_
a|`unistring`
a|
a|

a|`Value`
a|_Значение_
a|`int`
a|
a|

a|`Operation`
a|_Операция_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `A5D22D25-435D-4F08-BF02-B4E9F778709F`


a|`OptionColor`
a|_Настройка цвета варианта завершения_
a|`int`
a|
a|

|===

=== Дополнительные аттрибуты

Идентификатор: `94A7469D-0631-49BA-BE0A-B4099D6EA4C2`
Псевдоним: `AdditionalFields`
Тип секции: `coll`
Название: _Дополнительные аттрибуты_

.Поля секции Дополнительные аттрибуты
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`SectionId`
a|_Идентификатор секции_
a|`uniqueid`
a|
a|

a|`Field`
a|_Поле секции_
a|`string`
a|
a|

a|`Required`
a|_Обязательное поле_
a|`bool`
a|
a|

a|`ShowDialog`
a|_Показывать диалог_
a|`enum`
a|
a|.Значения
* Всегда = 0
* Никогда = 1
* Показывать если пустое = 2


|===

=== Локализации

Идентификатор: `C9A213ED-D185-431B-B057-1369DAEF83AA`
Псевдоним: `CompletionOptionsLocalizations`
Тип секции: `coll`
Название: _Локализации_

.Поля секции Локализации
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`LocaleID`
a|_Локализация_
a|`int`
a|
a|

a|`Name`
a|_Название_
a|`unistring`
a|
a|

|===

=== Настройки вида подчинённого задания

Идентификатор: `35C07C7B-E710-498D-A84B-74D07525A4CF`
Псевдоним: `ChildKindPresets`
Тип секции: `struct`
Название: _Настройки вида подчинённого задания_

.Поля секции Настройки вида подчинённого задания
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ChildTaskKindType`
a|_Режим создания подчинённого задания_
a|`enum`
a|
a|.Значения
* Как у родительского задания = 0
* Любого вида = 1
* Вид из списка = 2


|===

=== Виды, доступные для создания подчинённого задания

Идентификатор: `497CF9FD-5056-4F03-9A8B-74894DE7A0A3`
Псевдоним: `ChildKindSettings`
Тип секции: `tree`
Название: _Виды, доступные для создания подчинённого задания_

.Поля секции Виды, доступные для создания подчинённого задания
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Creatable`
a|_Создаваемый_
a|`bool`
a|
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Настройки маршрутизации

Идентификатор: `B207F7EC-DB61-4FC6-9323-8D4E45D6BF76`
Псевдоним: `RoutingPresets`
Тип секции: `struct`
Название: _Настройки маршрутизации_

.Поля секции Настройки маршрутизации
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`RoutingType`
a|_Маршрутизация_
a|`enum`
a|
a|.Значения
* По умолчанию = 0
* Онлайн задание = 1
* Задача Почтового клиента = 2
* Ссылка на задание = 3
* Письмо с описанием = 4


|===

=== Настройки вида подчиненной группы заданий

Идентификатор: `6468EDF0-47DD-4FFB-813E-26A26CB06342`
Псевдоним: `GroupChildKindPresets`
Тип секции: `struct`
Название: _Настройки вида подчиненной группы заданий_

.Поля секции Настройки вида подчиненной группы заданий
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ChildTaskGroupKindType`
a|_Режим создания подчиненной группы заданий_
a|`enum`
a|
a|.Значения
* Как у родительского задания = 0
* Любого вида = 1
* Вид из списка = 2


|===

=== Виды, доступные для создания подчиненной группы заданий

Идентификатор: `82F1045D-90F8-4FE8-BF1D-B311E84826E9`
Псевдоним: `GroupChildKindSettings`
Тип секции: `tree`
Название: _Виды, доступные для создания подчиненной группы заданий_

.Поля секции Виды, доступные для создания подчиненной группы заданий
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Creatable`
a|_Создаваемый_
a|`bool`
a|
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Настройки Почтового клиента

Идентификатор: `8E374C95-FB78-4777-ACBD-F3BFCD2A3766`
Псевдоним: `TaskRouting`
Тип секции: `struct`
Название: _Настройки Почтового клиента_

.Поля секции Настройки Почтового клиента
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`MessageXslt`
a|_Xslt письма о новом задании_
a|`string`
a|
a|

a|`ShowLinkedDocumentInMessage`
a|_Отображать связанный документ в письме_
a|`bool`
a|
a|

a|`MailAttachmentsMaxSize`
a|_Максимальный размер почтового сообщения (мб)_
a|`int`
a|
a|

|===

=== Согласование

Идентификатор: `03C27047-FD44-4D3D-B4CB-ABBF21A76E4C`
Псевдоним: `Reconciliation`
Тип секции: `struct`
Название: _Согласование_

.Поля секции Согласование
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Reconciliation`
a|_Согласование_
a|`refcardid`
a|
a|* Идентификатор типа: `04280BC4-A660-4AEB-866F-F3ECE579D945`
* Идентификатор секции: `35473281-BCEB-415A-8603-74549421037E`


a|`Stage`
a|_Этап_
a|`refcardid`
a|
a|* Идентификатор типа: `35E7139A-82B8-425D-AB14-ADC2DB757D7A`
* Идентификатор секции: `381CB937-019E-4413-A2BD-646BE7F7250E`
Поля ссылки: 
StageName

a|`Route`
a|_Маршрут_
a|`refcardid`
a|
a|* Идентификатор типа: `99DD6295-1B3D-4DA6-8256-8332D3E955C9`
* Идентификатор секции: `25B976F7-1C74-4D5C-B60A-7A8F4897A8CE`
Поля ссылки: 
RouteName

a|`Log`
a|_Ход согласования_
a|`refcardid`
a|
a|* Идентификатор типа: `24410C2C-3757-4E0D-839C-D86C2B2DAD66`
* Идентификатор секции: `30C984A9-A9C0-45E4-95D6-9D5FC22F389C`


a|`Loop`
a|_Цикл_
a|`int`
a|
a|

a|`DeleteOldVersion`
a|_Удалять старую версию при добавлении новой_
a|`bool`
a|
a|

a|`Comment`
a|_Комментарий_
a|`unitext`
a|
a|

a|`CommentFile`
a|_Файл комментария_
a|`fileid`
a|
a|

|===

=== Дополнительные согласующие

Идентификатор: `C9479B9D-59A5-4E29-8F05-112173AD3FBD`
Псевдоним: `AdditionalApprovers`
Тип секции: `coll`
Название: _Дополнительные согласующие_

.Поля секции Дополнительные согласующие
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Approver`
a|_Согласующий_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Дополнительные файлы

Идентификатор: `1C7DC1A3-8121-477A-B2A5-7335CA680B73`
Псевдоним: `AdditionalFiles`
Тип секции: `coll`
Название: _Дополнительные файлы_

.Поля секции Дополнительные файлы
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`File`
a|_Файл_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`
Поля ссылки: 
FileName

a|`AuthorID`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`CreationDate`
a|_Дата создания_
a|`datetime`
a|
a|

a|`LoopNum`
a|_Номер цикла_
a|`int`
a|
a|

a|`Stage`
a|_Этап_
a|`refcardid`
a|
a|* Идентификатор типа: `35E7139A-82B8-425D-AB14-ADC2DB757D7A`
* Идентификатор секции: `381CB937-019E-4413-A2BD-646BE7F7250E`


a|`Comment`
a|_Комментарий_
a|`unitext`
a|
a|

|===

=== Настройки дерева версий

Идентификатор: `530495CC-519F-44AA-8A3D-C387CB314B1C`
Псевдоним: `VersionTreeSettings`
Тип секции: `coll`
Название: _Настройки дерева версий_

.Поля секции Настройки дерева версий
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`FileId`
a|_Идентификатор файла_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`


a|`VersionToShow`
a|_Версия для отображения_
a|`refid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `F831372E-8A76-4ABC-AF15-D86DC5FFBE12`


|===

=== Файлы только для чтения

Идентификатор: `06E39866-C3CC-40A3-84C8-742CAFC47C52`
Псевдоним: `ReadonlyFiles`
Тип секции: `coll`
Название: _Файлы только для чтения_

.Поля секции Файлы только для чтения
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`File`
a|_Файл_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`


a|`AuthorID`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`CreationDate`
a|_Дата создания_
a|`datetime`
a|
a|

a|`LoopNum`
a|_Номер цикла_
a|`int`
a|
a|

a|`Stage`
a|_Этап_
a|`refcardid`
a|
a|* Идентификатор типа: `35E7139A-82B8-425D-AB14-ADC2DB757D7A`
* Идентификатор секции: `381CB937-019E-4413-A2BD-646BE7F7250E`


a|`Comment`
a|_Комментарий_
a|`unitext`
a|
a|

|===

