= Справочник шлюзов

Идентификатор: `C1887469-3D28-4EC6-84BD-7CAEA7607F0C`

Псевдоним: `GateList`

Название: _Справочник шлюзов_

== Секции карточки

=== Общая информация

Идентификатор: `42B598D5-B3F4-4349-B0E8-874EDB737ABE`
Псевдоним: `MainInfo`
Тип секции: `coll`
Название: _Общая информация_

.Поля секции Общая информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Название_
a|`unistring`
a|64
a|

a|`ServerClass`
a|_Класс_
a|`string`
a|100
a|

a|`ServerAssembly`
a|_Сборка содержашая класс_
a|`string`
a|255
a|

a|`UIClass`
a|_Класс UI_
a|`string`
a|100
a|

a|`ID`
a|_Идентификатор_
a|`uniqueid`
a|
a|

a|`DefaultSettings`
a|_Настройки по умолчанию_
a|`unistring`
a|2048
a|

a|`AddGateInNewProcess`
a|_Автоматически добавлять шлюз в новые процессы_
a|`bool`
a|
a|

|===

=== Дополнительная информация

Идентификатор: `533458CF-0700-42DB-8A4F-A0EE02F4B41F`
Псевдоним: `AdditionalInfo`
Тип секции: `struct`
Название: _Дополнительная информация_

.Поля секции Дополнительная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Definition`
a|_Данные описания шлюза_
a|`unitext`
a|
a|

a|`LicenseInfo`
a|_Информация о лицензии_
a|`unitext`
a|
a|

|===

