= Настройки Workflow

Идентификатор: `2DA5436F-2FD5-413C-8EC3-CA0D68B265C6`

Псевдоним: `Settings`

Название: _Настройки Workflow_

== Секции карточки

=== Настройки пользователя

Идентификатор: `32DC8D5C-46EE-4ECA-86FD-FAB43898A1F9`
Псевдоним: `UserSettings`
Тип секции: `struct`
Название: _Настройки пользователя_

.Поля секции Настройки пользователя
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ShowExportDialog`
a|_Показывать диалог при экспорте_
a|`bool`
a|
a|

a|`ShowImportDialog`
a|_Показывать диалог импорта_
a|`bool`
a|
a|

a|`ExportWithSubprocesses`
a|_Экспортировать процесс с подпроцессами_
a|`bool`
a|
a|

a|`ImportWithSubprocesses`
a|_Импортировать процесс с подпроцессами_
a|`bool`
a|
a|

a|`Value`
a|_Значение_
a|`bool`
a|
a|

|===

=== Сборки

Идентификатор: `37FCF8F2-0D29-4E9F-A61D-3CA5FE1A8404`
Псевдоним: `Assemblies`
Тип секции: `coll`
Название: _Сборки_

.Поля секции Сборки
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Name`
a|_Имя сборки_
a|`unistring`
a|2048
a|

a|`AssemblyID`
a|_Идентификатор сборки_
a|`uniqueid`
a|
a|

a|`AddInNewProcess`
a|_Автоматически добавлять сборку в новые шаблоны процессов_
a|`bool`
a|
a|

|===

=== Данные шлюзов

Идентификатор: `64EAEFBB-DFCD-4460-87C6-9CC93561033F`
Псевдоним: `GateSettings`
Тип секции: `coll`
Название: _Данные шлюзов_

.Поля секции Данные шлюзов
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`GateID`
a|_Идентификатор_
a|`uniqueid`
a|
a|

|===

=== Экземпляры шлюза

Идентификатор: `AE9BFD74-BFAE-4648-8110-B155C2E9F316`
Псевдоним: `Instances`
Тип секции: `coll`
Название: _Экземпляры шлюза_

.Поля секции Экземпляры шлюза
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Settings`
a|_Настройки_
a|`unistring`
a|2048
a|

|===

=== Идентификаторы изменившихся карточек

Идентификатор: `BE69A08B-97BF-431E-8831-5F7BB6A60346`
Псевдоним: `ChangedCards`
Тип секции: `coll`
Название: _Идентификаторы изменившихся карточек_

.Поля секции Идентификаторы изменившихся карточек
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`CardID`
a|_Идентификатор карточки_
a|`uniqueid`
a|
a|

a|`ChangeDate`
a|_Дата изменения_
a|`datetime`
a|
a|

|===

=== Информация о сервисах Workflow

Идентификатор: `B4A2559B-45FD-4ABA-919F-0F170CCDDB5D`
Псевдоним: `Services`
Тип секции: `coll`
Название: _Информация о сервисах Workflow_

.Поля секции Информация о сервисах Workflow
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`ServiceID`
a|_Идентификатор сервиса_
a|`unistring`
a|50
a|

a|`WorkPart`
a|_Доля работы_
a|`int`
a|
a|

a|`State`
a|_Состояние сервиса_
a|`int`
a|
a|

a|`LastAccessTime`
a|_Время последнего доступа_
a|`datetime`
a|
a|

a|`Session`
a|_Идентификатор сессии_
a|`uniqueid`
a|
a|

a|`ProcessedLBound`
a|_Обработанная нижняя граница_
a|`int`
a|
a|

a|`ProcessedUBound`
a|_Обработанная верхняя граница_
a|`int`
a|
a|

a|`AssignedLBound`
a|_Назначенная нижняя граница_
a|`int`
a|
a|

a|`AssignedUBound`
a|_Назначенная верхняя граница_
a|`int`
a|
a|

|===

